### Registration

POST http://localhost:8090/api/v1/auth/registration
Content-Type: application/json

{
  "name":"Testjon",
  "surname":"Testov",
  "email":"test@gmail.com",
  "password":"123456"
}

### Verification
GET http://localhost:8090/api/v1/auth/verification/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY5NzY4OTE4NCwiZXhwIjoxNjk3Nzc1NTg0LCJpc3MiOiJVc2VmdWwgQ29kZXMgcHJvZHVjdGlvbiJ9.umnBr_5R06D2CIu9TVtHMjrK7AXN8TgQUmVrTZtlgJw

### Login
POST http://localhost:8090/api/v1/auth/login
Content-Type: application/json

{
  "email":"test@gmail.com",
  "password":"123456"
}