###
POST http://localhost:8090/api/v1/user/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY5NzY0MjQ0MCwiZXhwIjoxNjk3NzI4ODQwLCJpc3MiOiJVc2VmdWwgQ29kZXMgcHJvZHVjdGlvbiJ9.zXd8bs1Xn7fzlGDbku2OCbtWbtfTvXtJPqEYK0Ac1cc

{
  "name":"dossi",
  "surname":"Yorqulov",
  "email":"dossi@gmail.com",
  "password":"123456"
}

###
GET http://localhost:8090/api/v1/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkb3NzaUBnbWFpbC5jb20iLCJpYXQiOjE2OTc2NDU0MzUsImV4cCI6MTY5NzczMTgzNSwiaXNzIjoiVXNlZnVsIENvZGVzIHByb2R1Y3Rpb24ifQ.bKshwRlaPD0lrRziouUC7LN_SuY6wBzWZNz1BDtzoG0


###
GET http://localhost:8090/api/v1/user/ac64c1aa-0aa3-40db-9c94-d26ef373f08a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkb3NzaUBnbWFpbC5jb20iLCJpYXQiOjE2OTc2NDU0MzUsImV4cCI6MTY5NzczMTgzNSwiaXNzIjoiVXNlZnVsIENvZGVzIHByb2R1Y3Rpb24ifQ.bKshwRlaPD0lrRziouUC7LN_SuY6wBzWZNz1BDtzoG0


###
PUT http://localhost:8090/api/v1/user/update/ac64c1aa-0aa3-40db-9c94-d26ef373f08a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkb3NzaUBnbWFpbC5jb20iLCJpYXQiOjE2OTc2NDU0MzUsImV4cCI6MTY5NzczMTgzNSwiaXNzIjoiVXNlZnVsIENvZGVzIHByb2R1Y3Rpb24ifQ.bKshwRlaPD0lrRziouUC7LN_SuY6wBzWZNz1BDtzoG0

{
  "name": "alijon update",
  "surname": "Yorqulov",
  "email":"alijonupdate@gmail.com",
  "password":"123456"
}